import { SignatureState, ThemeConfig } from "./types";

export const FONTS = [
  {
    label: "Great Vibes",
    value: "great-vibes",
    url:
      "https://cdn.jsdelivr.net/npm/@fontsource/great-vibes@5.0.8/files/great-vibes-latin-400-normal.woff",
    category: "Script",
  },
  {
    label: "Dancing Script",
    value: "dancing-script",
    url:
      "https://cdn.jsdelivr.net/npm/@fontsource/dancing-script@5.0.8/files/dancing-script-latin-400-normal.woff",
    category: "Script",
  },
  {
    label: "Allura",
    value: "allura",
    url:
      "https://cdn.jsdelivr.net/npm/@fontsource/allura@5.0.20/files/allura-latin-400-normal.woff",
    category: "Script",
  },
  {
    label: "Sacramento",
    value: "sacramento",
    url:
      "https://cdn.jsdelivr.net/npm/@fontsource/sacramento@5.0.8/files/sacramento-latin-400-normal.woff",
    category: "Script",
  },
  {
    label: "Lobster",
    value: "lobster",
    url:
      "https://cdn.jsdelivr.net/npm/@fontsource/lobster@5.0.8/files/lobster-latin-400-normal.woff",
    category: "Brand",
  },
  {
    label: "Pacifico",
    value: "pacifico",
    url:
      "https://cdn.jsdelivr.net/npm/@fontsource/pacifico@5.0.8/files/pacifico-latin-400-normal.woff",
    category: "Brand",
  },
  {
    label: "Permanent Marker",
    value: "permanent-marker",
    url:
      "https://cdn.jsdelivr.net/npm/@fontsource/permanent-marker@5.0.8/files/permanent-marker-latin-400-normal.woff",
    category: "Brand",
  },
  {
    label: "Ma Shan Zheng",
    value: "ma-shan-zheng",
    url:
      "https://cdn.jsdelivr.net/npm/@fontsource/ma-shan-zheng@5.0.13/files/ma-shan-zheng-chinese-simplified-400-normal.woff",
    category: "Local",
  },
  {
    label: "Satisfy",
    value: "satisfy",
    url:
      "https://cdn.jsdelivr.net/npm/@fontsource/satisfy@5.0.8/files/satisfy-latin-400-normal.woff",
    category: "Script",
  },
  {
    label: "Courgette",
    value: "courgette",
    url:
      "https://cdn.jsdelivr.net/npm/@fontsource/courgette@5.0.8/files/courgette-latin-400-normal.woff",
    category: "Script",
  },
];

export const DEFAULT_CHAR_COLORS = [
  "#ef4444",
  "#f97316",
  "#f59e0b",
  "#84cc16",
  "#10b981",
  "#06b6d4",
  "#3b82f6",
  "#8b5cf6",
  "#d946ef",
];

const buildDefaultMultiColors = (text: string): string[] =>
  Array.from(
    { length: text.length },
    (_, i) => DEFAULT_CHAR_COLORS[i % DEFAULT_CHAR_COLORS.length],
  );

const buildPepsiColors = (text: string): string[] => {
  const len = text.length;
  const black = "#000000";
  const white = "#ffffff";
  return Array.from(
    { length: len },
    (_, i) => (i < 4 ? black : white),
  );
};

export const THEMES: Record<string, ThemeConfig> = {
  default: {
    bg: "#ffffff",
    bg2: "#ffffff",
    bgMode: "solid",
    bgTransparent: false,
    stroke: "#333333",
    strokeEnabled: true,
    fillMode: "single",
    fill1: "#333333",
    font: "great-vibes",
    useGlow: false,
    useShadow: false,
    borderRadius: 12,
    texture: "none",
  },
  school: {
    bg: "#ffffff",
    bg2: "#e5e7eb",
    bgMode: "solid",
    bgTransparent: false,
    stroke: "#1e3a8a",
    strokeEnabled: true,
    fillMode: "single",
    fill1: "#1e3a8a",
    font: "dancing-script",
    useGlow: false,
    useShadow: false,
    borderRadius: 8,
    texture: "lines",
    texColor: "#3b82f6",
    texOpacity: 0.3,
    texSize: 26,
  },
  blueprint: {
    bg: "#1e3a8a",
    bg2: "#1e3a8a",
    bgMode: "solid",
    bgTransparent: false,
    stroke: "#ffffff",
    strokeEnabled: true,
    fillMode: "single",
    fill1: "#ffffff",
    font: "sacramento",
    useGlow: false,
    useShadow: false,
    borderRadius: 0,
    texture: "grid",
    texColor: "#ffffff",
    texOpacity: 0.2,
    texSize: 30,
  },
  chinese: {
    bg: "#dc2626",
    bg2: "#dc2626",
    bgMode: "solid",
    bgTransparent: false,
    stroke: "#fef3c7",
    strokeEnabled: true,
    fillMode: "single",
    fill1: "#fef3c7",
    font: "ma-shan-zheng",
    useGlow: false,
    useShadow: false,
    borderRadius: 4,
    texture: "grid",
    texColor: "#680303",
    texOpacity: 0.4,
    texSize: 25,
    texThickness: 3,
  },
  cyber: {
    bg: "#0f172a",
    bg2: "#1e293b",
    bgMode: "gradient",
    bgTransparent: false,
    stroke: "#facc15",
    strokeEnabled: true,
    fillMode: "gradient",
    fill1: "#facc15",
    fill2: "#d946ef",
    font: "pacifico",
    useGlow: true,
    useShadow: true,
    borderRadius: 4,
    texture: "cross",
    texColor: "#334155",
    texSize: 38,
    texOpacity: 0.45,
  },
  pepsi: {
    bg: "#e32934",
    bg2: "#004b93",
    bgMode: "gradient",
    bgTransparent: false,
    stroke: "#000000",
    strokeEnabled: true,
    // Pepsi should default to multi-color fill and stroke
    fillMode: "multi",
    fill1: "#000000",
    fill2: "#000000",
    strokeMode: "multi",
    charColorsFn: buildPepsiColors,
    strokeCharColorsFn: buildPepsiColors,
    font: "lobster",
    useGlow: false,
    useShadow: false,
    borderRadius: 16,
    texture: "none",
  },
  coke: {
    bg: "#f40009",
    bg2: "#f40009",
    bgMode: "solid",
    bgTransparent: false,
    stroke: "#000000",
    strokeEnabled: true,
    fillMode: "single",
    fill1: "#000000",
    font: "lobster",
    useGlow: false,
    useShadow: false,
    borderRadius: 20,
    texture: "none",
  },
  sprite: {
    bg: "#008b47",
    bg2: "#f8cd2b",
    bgMode: "gradient",
    bgTransparent: false,
    stroke: "#f8cd2b",
    strokeEnabled: true,
    fillMode: "single",
    fill1: "#f8cd2b",
    font: "permanent-marker",
    useGlow: false,
    useShadow: true,
    borderRadius: 8,
    texture: "dots",
    texColor: "#ffffff",
    texOpacity: 0.2,
    texThickness: 2,
    texSize: 21,
  },
  ink: {
    bg: "#f5f5f4",
    bg2: "#e5e7eb",
    bgMode: "solid",
    bgTransparent: false,
    stroke: "#1f2937",
    strokeEnabled: true,
    fillMode: "single",
    fill1: "#111827",
    font: "ma-shan-zheng",
    useGlow: false,
    useShadow: false,
    borderRadius: 12,
    texture: "lines",
    texColor: "#d4d4d4",
    texOpacity: 0.8,
    texSize: 24,
  },
  jade: {
    bg: "#d1fae5",
    bg2: "#a7f3d0",
    bgMode: "gradient",
    bgTransparent: false,
    stroke: "#064e3b",
    strokeEnabled: true,
    fillMode: "single",
    fill1: "#064e3b",
    font: "ma-shan-zheng",
    useGlow: false,
    useShadow: false,
    borderRadius: 16,
    texture: "dots",
    texColor: "#047857",
    texOpacity: 0.25,
    texSize: 18,
  },
  laser: {
    bg: "#036a77",
    bg2: "#411281",
    bgMode: "gradient",
    bgTransparent: false,
    stroke: "#00ffff",
    strokeEnabled: true,
    fillMode: "gradient",
    fill1: "#00ffff",
    fill2: "#ff00ff",
    font: "sacramento",
    useGlow: true,
    useShadow: true,
    borderRadius: 14,
    texture: "grid",
    texColor: "#00ffff",
    texOpacity: 0.8,
    texThickness: 1,
    texSize: 84,
  },
  rainbow: {
    bg: "#ffffff",
    bg2: "#ffffff",
    bgMode: "solid",
    bgTransparent: false,
    stroke: "#333333",
    strokeEnabled: true,
    fillMode: "multi",
    fill1: "#333333",
    font: "dancing-script",
    useGlow: false,
    useShadow: false,
    borderRadius: 16,
    charColorsFn: buildDefaultMultiColors,
    texture: "none",
  },
  practice: {
    bg: "#fef5f5",
    bg2: "#fef5f5",
    bgMode: "solid",
    bgTransparent: false,
    stroke: "#d9534f",
    strokeEnabled: true,
    fillMode: "single",
    fill1: "#d9534f",
    font: "ma-shan-zheng",
    useGlow: false,
    useShadow: false,
    borderRadius: 8,
    texture: "mizige",
    texColor: "#e6b8b8",
    texOpacity: 0.6,
    texSize: 120,
    texThickness: 1.5,
    useHanziData: true,
  },
};

export const INITIAL_STATE: SignatureState = {
  text: "Signature",
  font: "great-vibes",
  fontSize: 120,
  speed: 1.2,
  bg: "#ffffff",
  bg2: "#ffffff",
  bgMode: "solid",
  bgTransparent: false,
  borderRadius: 12,
  cardPadding: 24,
  bgSizeMode: "auto",
  bgWidth: null,
  bgHeight: null,
  stroke: "#333333",
  strokeEnabled: true,
  strokeMode: "single",
  stroke2: "#333333",
  strokeCharColors: [],
  fillMode: "single",
  fill1: "#333333",
  fill2: "#ec4899",
  charColors: [],
  texture: "none",
  texColor: "#cbd5e1",
  texSize: 20,
  texThickness: 1,
  texOpacity: 0.5,
  useGlow: false,
  useShadow: false,
};
